spam_words = ['adult',
              'date',
              'sex',
              'sext',
              'dick',
              'cock',
              'pussy',
              'vagina',
              'porn',
              'girl',
              'girls',
              'fuck', 'fucked',
              'fucking',
              'couple',
              'wоmen',
              'woman',
              'cialis',
              'viagra',
              'http',
              'https']
