version: "3.7"

services:
  postgresql:
    container_name: postgresql

    image: postgres:14.3-bullseye
    restart: always

    volumes:
      - postgresql_data:/var/lib/postgresql/data

    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678

  django:
    container_name: django
    build: .
    # command: ENTERYPOINT
    volumes:
      - static_volume:/app/static

    depends_on:
      - postgresql

  nginx:
    container_name: nginx
    build: ./nginx/.
    volumes:
      - static_volume:/app/static
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - django

volumes:
  static_volume:
  postgresql_data:
