version: "3.7"

services:
  postgresql:
    image: postgres:13.4-buster
    restart: always

    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678

  django:
    container_name: django
    build: .
    # command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - static_volume:/app/static
    depends_on:
      - postgresql

  nginx:
    container_name: nginx
    build: ./nginx/.
    volumes:
      - static_volume:/app/static
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - django

volumes:
  static_volume:
