# Generated by Django 2.2.1 on 2019-05-26 03:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wallOf', '0002_auto_20190510_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelposts',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='modelposts',
            name='emotion',
            field=models.TextField(max_length=240),
        ),
    ]
