# Generated by Django 2.2.1 on 2019-05-26 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallOf', '0005_auto_20190525_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelposts',
            name='down_vote',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='modelposts',
            name='up_vote',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='modelposts',
            name='title',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='modelposts',
            name='vote',
            field=models.CharField(blank=True, choices=[('vote_here', 'vote_here'), ('down', 'down')], default=0, max_length=4, null=True),
        ),
    ]
