# Generated by Django 2.2.1 on 2019-05-26 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallOf', '0006_auto_20190525_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelposts',
            name='down_vote',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='modelposts',
            name='up_vote',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='modelposts',
            name='vote',
            field=models.IntegerField(default=0),
        ),
    ]
