# Generated by Django 2.2.1 on 2019-05-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallOf', '0007_auto_20190526_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelposts',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
