# Generated by Django 2.2.1 on 2019-05-27 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallOf', '0009_auto_20190526_0409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelposts',
            name='vote',
        ),
    ]
