# Generated by Django 2.2.1 on 2019-05-27 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallOf', '0010_remove_modelposts_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelposts',
            name='up_vote',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
