# Generated by Django 2.2.1 on 2019-05-27 23:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wallOf', '0011_auto_20190526_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelposts',
            name='only_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
