# Generated by Django 2.2.1 on 2019-05-27 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallOf', '0012_modelposts_only_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelposts',
            old_name='date',
            new_name='date_and_time',
        ),
        migrations.AlterField(
            model_name='modelposts',
            name='only_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
