# Generated by Django 2.2.1 on 2019-05-28 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallOf', '0013_auto_20190527_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelposts',
            name='rant',
            field=models.TextField(blank=True, max_length=240),
        ),
    ]
