# Generated by Django 2.2.1 on 2019-05-28 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallOf', '0014_auto_20190527_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelposts',
            name='rant',
            field=models.TextField(max_length=240),
        ),
    ]
