# Generated by Django 2.2.1 on 2019-05-29 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallOf', '0016_auto_20190528_0051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelposts',
            old_name='rant',
            new_name='frustration',
        ),
    ]
