# Generated by Django 2.2.1 on 2019-06-03 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallOf', '0017_auto_20190529_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelposts',
            name='secrete',
            field=models.TextField(max_length=240, null=True),
        ),
    ]
