# Generated by Django 2.2.1 on 2019-06-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallOf', '0018_modelposts_secrete'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelSecretes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('secrete', models.TextField(max_length=240)),
                ('date_and_time', models.DateTimeField(auto_now_add=True)),
                ('only_date', models.DateField(auto_now_add=True, null=True)),
                ('up_vote', models.PositiveIntegerField(blank=True, default=0)),
                ('down_vote', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='modelposts',
            name='secrete',
        ),
    ]
