# Generated by Django 2.2.1 on 2019-06-04 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallOf', '0019_auto_20190603_0243'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelAdvice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('advice', models.TextField(max_length=240)),
                ('date_and_time', models.DateTimeField(auto_now_add=True)),
                ('only_date', models.DateField(auto_now_add=True, null=True)),
                ('up_vote', models.PositiveIntegerField(blank=True, default=0)),
                ('down_vote', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
