# Generated by Django 2.2.1 on 2019-06-26 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallOf', '0020_modeladvice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelposts',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
