# Generated by Django 2.2.1 on 2019-06-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallOf', '0023_auto_20190627_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelposts',
            name='up_vote',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
