# Generated by Django 2.2.1 on 2019-06-27 08:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wallOf', '0026_auto_20190627_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelposts',
            name='only_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
