# Generated by Django 2.2.1 on 2019-07-13 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallOf', '0032_auto_20190702_0048'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ModelSecretes',
            new_name='Modelsecrets',
        ),
        migrations.RenameField(
            model_name='modelsecrets',
            old_name='secrete',
            new_name='secret',
        ),
        migrations.DeleteModel(
            name='ModelComment',
        ),
    ]
