# Generated by Django 2.2.1 on 2019-08-28 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallOf', '0033_auto_20190713_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelposts',
            name='RED_FLAG',
            field=models.BooleanField(default=False),
        ),
    ]
