# Generated by Django 2.2.7 on 2019-11-29 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallOf', '0038_modelspam'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModelSpam',
        ),
    ]
