# Generated by Django 3.0.6 on 2020-05-20 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallOf', '0040_modelspam'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelGraduation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('memory', models.TextField(max_length=240, verbose_name='memory')),
                ('date_and_time', models.DateTimeField(auto_now_add=True)),
                ('only_date', models.DateField(auto_now_add=True)),
                ('up_vote', models.IntegerField(blank=True, default=0)),
                ('down_vote', models.IntegerField(blank=True, default=0)),
                ('RED_FLAG', models.BooleanField(default=False)),
            ],
        ),
    ]
