# Generated by Django 3.0.6 on 2020-05-20 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallOf', '0041_modelgraduation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModelGraduation',
        ),
    ]
